# Generated by Django 3.2.6 on 2021-08-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActaReun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acgrupo', models.CharField(max_length=30, verbose_name='Grupo')),
                ('acfecha', models.DateField(null=True, verbose_name='Fecha de Acta de Reunión')),
                ('acasistencia', models.PositiveIntegerField(verbose_name='Asistecia')),
                ('acresumen', models.TextField(verbose_name='Resumen')),
            ],
            options={
                'verbose_name': 'Acta de Reunion',
                'verbose_name_plural': 'Actas de Reuniones',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30, verbose_name='Nombres')),
                ('eapellido', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('eedad', models.PositiveIntegerField(verbose_name='Edad')),
                ('egrupo', models.CharField(max_length=20, verbose_name='Grupo')),
                ('Anno_Academic', models.CharField(choices=[('1er', 'Primero'), ('2do', 'Segundo'), ('3er', 'Tercero'), ('4to', 'Cuarto'), ('5to', 'Quinto')], max_length=10, unique=True, verbose_name='Año Academico')),
                ('emilitancia', models.CharField(choices=[('No', 'no'), ('Si', 'si')], max_length=2, verbose_name='Militancia')),
                ('eautoevaluacion', models.TextField(unique=True, verbose_name='Autoevaluación')),
                ('evaluacion', models.CharField(choices=[('B', 'Bien'), ('R', 'Regular'), ('M', 'Mal')], max_length=1, verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Integral',
                'verbose_name_plural': 'Evaluaciones Integrales',
            },
        ),
        migrations.CreateModel(
            name='EventEstudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evnombre', models.CharField(max_length=150, verbose_name='Nombre del Evento Estudiantil')),
                ('evtipo', models.CharField(max_length=50, verbose_name='Tipo del Evento Estudiantil')),
                ('evcantEstu', models.PositiveIntegerField(verbose_name='Cantidad del Estudiantes a Participar')),
                ('efecha', models.DateTimeField(null=True, verbose_name='Fecha del Evento Estudiantil')),
                ('evlugar', models.CharField(max_length=100, verbose_name='Luga del Evento Estudiantil')),
            ],
            options={
                'verbose_name': 'Evento Estudiantil',
                'verbose_name_plural': 'Eventos Estudiantiles',
            },
        ),
    ]
